# Generated by Django 4.1.7 on 2023-03-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partlibary", "0001_initial"),
        ("accounts", "0003_customuser_incoming_part_libary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="part_libary_lookup",
            field=models.ManyToManyField(related_name="lookup", to="partlibary.part"),
        ),
    ]
