# Generated by Django 4.1.7 on 2023-03-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("package", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("part_number", models.CharField(max_length=100)),
                ("qty", models.IntegerField()),
                ("note", models.TextField()),
                ("location", models.TextField()),
                ("data_sheet", models.TextField()),
            ],
        ),
    ]
