# Generated by Django 4.1.7 on 2023-03-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partlibary", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="part_libary",
            field=models.ManyToManyField(to="partlibary.part"),
        ),
    ]
